"""initial migration

Revision ID: 832c0fa0893d
Revises: 
Create Date: 2017-09-11 00:01:20.747615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832c0fa0893d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('upvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvoter', sa.Integer(), nullable=True),
    sa.Column('upvoted', sa.Integer(), nullable=True),
    sa.Column('answerid', sa.Integer(), nullable=True),
    sa.Column('descr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('ups', sa.Integer(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('followed_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('quesposans', sa.Integer(), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.Column('belongtoques', sa.Integer(), nullable=True),
    sa.Column('belongtoquesbody', sa.Text(), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ques_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.Column('quesid', sa.Integer(), nullable=True),
    sa.Column('ansid', sa.Integer(), nullable=True),
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.Column('eventuserid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ansid'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['articleid'], ['article.id'], ),
    sa.ForeignKeyConstraint(['eventuserid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['quesid'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ques_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['ques_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'ques_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join')
    op.drop_table('event')
    op.drop_table('answer')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('upvote')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('article')
    # ### end Alembic commands ###
